# Generated by Django 5.1.2 on 2024-11-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='bandas/')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('portada', models.ImageField(upload_to='albumes/')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='discografia.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='canciones/')),
                ('duracion', models.CharField(editable=False, max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='canciones/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='discografia.album')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='discografia.banda')),
            ],
        ),
    ]
