# Generated by Django 5.1.2 on 2024-11-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discografia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.CharField(default='Rock', max_length=50),
            preserve_default=False,
        ),
    ]
